database/api/api.go
database/node.go
truffle/test/01_wallet.js
truffle/test/02_transaction.js
truffle/test/03_smart_contract.js
truffle/test/04_workload.js
truffle/test/05_eth_api.js
truffle/truffle.js

* [(no apply)] Updated all relevant documentation in docs

[#65] Set ethCfg.NetworkId as Genesis.Config.ChainId

---

cmd/lightchain/main.go
consensus/abci.go
consensus/api/api.go
consensus/init.go
consensus/node.go
database/database.go
database/events.go
database/init.go
database/node.go
log/logger.go
node/init.go
node/node.go

Removes also a lot of duplicate unncessary loggings.
Fixes scenarios where we said "transaction valid" but it failed...
Adds logging for failed cases.

#61 Adds context to all logging across pkgs and corrects wording.

---

database/database.go
database/events.go

* (no_required) Updated all relevant documentation in docs
* (no_required) Wrote tests
**Applied changes**
In order to improve the consistency of the code, it was replaced the usage of ethereum logger in favour of the engine logger

#74 Replacing last usages of ethereum logger by engine logger

---

README.md

#70 Adding documentation to work around corrupted local state

---

truffle/contracts/HelloBlockchainWorld.sol
truffle/contracts/Migrations.sol
truffle/migrations/1_initial_migration.js
truffle/migrations/2_deploy_hello_blockchain_world.js
truffle/package-lock.json
truffle/package.json
truffle/test/01_wallet.js
truffle/test/02_transaction.js
truffle/test/03_smart_contract.js
truffle/test/04_workload.js
truffle/test/05_eth_api.js
truffle/test/utils.js

Updates Truffle to 5.0 and Web3 to 1.0, migrates tests

---

truffle/test/06_double_spend.js

#113 Adds 06_double_spend.js simplified test.

---

network/mainnet/database/genesis.go

#106 Adding token allocation to mainnet genesis file

---

Makefile

[NOTASK] Improve build script

---

scripts/init.sh
scripts/run.sh
truffle/test/02_transaction.js
truffle/test/04_workload.js
truffle/test/06_double_spend.js

[NOTASK] Reduce total cost of running truffle test suite

---

README.md
cmd/lightchain/main.go
docs/cmd/auto_generated/lightchain_init.md
docs/cmd/auto_generated/lightchain_run.md
docs/cmd/auto_generated/lightchain_simulate.md

* [x ] fixes https://github.com/lightstreams-network/lightchain/issues/49 makes datadir flag optional and default to ~/.lightchain

feat: makes datadir flag optional and default to ~/.lightchain

---

README.md

Include help section

---

Makefile

Makes Makefile self-documenting
```sh
➜  lightchain git:(feat/makefile) make
help                           Prints this help message
all                            Downloads dependencies and install lightchain
check-tools                    Check that required tools are installed
install                        Install lightchain
build                          Build lightchain
clean                          Clean binaries
build-dev                      (Dev) Build lightchain
gen-bindings                   (Dev) Generate bindings
get_vendor_deps                Download dependencies
docker                         Build docker image for lightchain
```

feat: makes makefile self documenting

---

Gopkg.lock
Gopkg.toml
database/blockstate.go

upgrade geth

---

consensus/abci.go
database/blockstate.go
database/database.go
database/state.go
truffle/contracts/HelloBlockchainWorld.sol
truffle/test/03_smart_contract.js

Persist() returns newly constructed, persisted Block.

#152 Fixes `log.BlockHash = bs.header.Root`.

---

database/database.go
scripts/run.sh
truffle/package-lock.json
truffle/package.json
truffle/test/05_eth_api.js

#133 Enable ethereum debug api when it is requested

---

cmd/lightchain/init.go
cmd/lightchain/run.go
consensus/config.go

#135 catching and handling consensus config loading error

---

cmd/lightchain/init.go
fs/io.go

#98 Adding confirmation before removing folder

---

network/mainnet/consensus/config.go
network/sirius/consensus/config.go
network/standalone/consensus/config.go

Correlate client consensus timeouts to remove disturbing timeout messages

#136 Correlate timeouts to network empty block intervals

---

Gopkg.lock
Gopkg.toml
cmd/lightchain/run.go
cmd/lightchain/version.go
database/database.go
network/mainnet/consensus/genesis.go
network/sirius/consensus/genesis.go

#161 Upgrades Tendermint to version v0.31.5.

---

consensus/api/api.go
consensus/node.go
network/standalone/consensus/config.go
node/node.go
truffle/test/05_eth_api.js

#166 Replacing usage of consensus RPC calls by direct method calls

---

cmd/lightchain/version.go

#171 Changes version to 1.2.0 Rock && Roll.

---

cmd/lightchain/version.go

#171 Removes "-beta" from `lightchain version` cmd.

---

consensus/node.go

#94 Implement consensus db closing logic

---

Dockerfile
Makefile
network/sirius/consensus/config.go
network/standalone/consensus/config.go

Max package size

---

Dockerfile
cmd/lightchain/version.go

[NOTASK] Update version

---

cmd/lightchain/version.go
consensus/api/api.go
database/api/public_eth_api.go
database/api/public_net.go
database/database.go

#189 Fetch net peers from consensusApi

---

network/sirius/database/genesis.go
network/standalone/database/genesis.go

#201 Enable constantinople fork on Standalone and Sirius.

---

network/sirius/database/keystore.go

Removed Sirius test account
